### PR TITLE
Fix prewarming

### LINKED ISSUE #659: Preheat Error after deploy - undefined local variable or method `cfn' for #<Jets::Preheat:>
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System | public.ecr.aws/sam/build-ruby3.2:latest-arm64 |
| Jets             | 4.0.1 |
| Ruby             | 3.2 |

---

## Expected Behavior

After upgrade to 4.0.1 from v3, I ran the `jets deploy` command and expected the deploy to finish successfully.

## Current Behavior

After UPDATE_COMPLETE, An error occurred when starting Preheat Job.

## Step-by-step reproduction instructions

```
10:57:37AM DELETE_IN_PROGRESS AWS::Lambda::LayerVersion GemLayer 
10:57:37AM UPDATE_COMPLETE AWS::CloudFormation::Stack ApiGateway 
10:57:38AM DELETE_COMPLETE AWS::Lambda::LayerVersion GemLayer 
10:57:38AM UPDATE_COMPLETE AWS::CloudFormation::Stack *********** 
Stack success status: UPDATE_COMPLETE
Time took: 1m 23s
Prewarming application.
/var/lang/lib/ruby/gems/3.2.0/gems/jets-4.0.1/lib/jets/preheat.rb:94:in `all_functions': undefined local variable or method `cfn' for #<Jets::Preheat:0x0000ffffa2bc0cf8 @options={:mute=>true, :mute_output=>true, :invocation_type=>"Event", :lambda_proxy=>false}> (NameError)

      parent_stack = cfn.describe_stack_resources(stack_name: Jets::Names.parent_stack_name)
                     ^^^
        from /var/lang/lib/ruby/gems/3.2.0/gems/memoist-0.16.2/lib/memoist.rb:169:in `all_functions'
        from /var/lang/lib/ruby/gems/3.2.0/gems/jets-4.0.1/lib/jets/preheat.rb:32:in `warm_all'
        from /var/lang/lib/ruby/gems/3.2.0/gems/jets-4.0.1/lib/jets/preheat.rb:15:in `warm_all'
        from /var/lang/lib/ruby/gems/3.2.0/gems/jets-4.0.1/lib/jets/internal/app/jobs/jets/preheat_job.rb:51:in `warm'
        from /var/lang/lib/ruby/gems/3.2.0/gems/jets-4.0.1/lib/jets/job/base.rb:31:in `perform_now'
        from /var/lang/lib/ruby/gems/3.2.0/gems/jets-4.0.1/lib/jets/internal/app/jobs/jets/preheat_job.rb:59:in `prewarm!'
        from /var/lang/lib/ruby/gems/3.2.0/gems/jets-4.0.1/lib/jets/cfn/ship.rb:108:in `prewarm'
        from /var/lang/lib/ruby/gems/3.2.0/gems/jets-4.0.1/lib/jets/cfn/ship.rb:46:in `run'
        from /var/lang/lib/ruby/gems/3.2.0/gems/jets-4.0.1/lib/jets/commands/deploy.rb:75:in `ship'
        from /var/lang/lib/ruby/gems/3.2.0/gems/jets-4.0.1/lib/jets/commands/deploy.rb:36:in `run'
        from /var/lang/lib/ruby/gems/3.2.0/gems/jets-4.0.1/lib/jets/commands/main.rb:27:in `deploy'
        from /var/lang/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /var/lang/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/lang/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /var/lang/lib/ruby/gems/3.2.0/gems/jets-4.0.1/lib/jets/commands/base.rb:38:in `dispatch'
        from /var/lang/lib/ruby/gems/3.2.0/gems/jets-4.0.1/lib/jets/commands/base.rb:27:in `perform'
        from /var/lang/lib/ruby/gems/3.2.0/gems/jets-4.0.1/lib/jets/cli.rb:28:in `start'
        from /var/lang/lib/ruby/gems/3.2.0/gems/jets-4.0.1/lib/jets/cli.rb:5:in `start'
        from /var/lang/lib/ruby/gems/3.2.0/gems/jets-4.0.1/exe/jets:14:in `<top (required)>'
        from /var/lang/bin/jets:25:in `load'
        from /var/lang/bin/jets:25:in `<main>'
```

## Code Sample

nothing.

## Solution Suggestion

nothing.

### PR DESCRIPTION
**Pull request by tongueroo**
This is a 🐞 bug fix.

- [ ] I've added tests (if it's a bug, feature or enhancement)
- [ ] I've adjusted the documentation (if it's a feature or enhancement)
- [ ] The test suite passes (run `bundle exec rspec` to verify this)

## Summary

Fix prewarming, when `config.prewarm.concurrency = 1`

Note: Think may simplify prewarm config options in the next major release of Jets v5.

## Context

Fixes #659

## How to Test

config/application.rb

```ruby
Jets.application.configure do
  # ...
  config.prewarm.concurrency = 1
end

## Version Changes

Patch

### CODE REVIEW

**Comment by tongueroo** [comment]
Released in jets 4.0.2
